// Auto-generated from the mini-market product list. Names copied verbatim (Arabic).
import type { ImportItem } from "./warehouse-import-data";

export const MINIMARKET_CATEGORIES = [
  "شيبسات ميني ماركت",
  "بسكويت ميني ماركت",
  "حلويات ميني ماركت",
  "شوكولاتة ميني ماركت",
  "عصيرات ميني ماركت",
] as const;

export const MINIMARKET_ITEMS: ImportItem[] = [
  { nameAr: "ليز ماكس اجنحة شيكاجو", sku: "CHP-001", category: "شيبسات ميني ماركت" },
  { nameAr: "دوريتوس", sku: "CHP-002", category: "شيبسات ميني ماركت" },
  { nameAr: "شيتوس", sku: "CHP-003", category: "شيبسات ميني ماركت" },
  { nameAr: "شيتوس بالليمون", sku: "CHP-004", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز مانجا", sku: "CHP-005", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز ماكس حار", sku: "CHP-006", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز ملح وخل", sku: "CHP-007", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز شطة وليمون", sku: "CHP-008", category: "شيبسات ميني ماركت" },
  { nameAr: "فورنو بالزبادي والأعشاب", sku: "CHP-009", category: "شيبسات ميني ماركت" },
  { nameAr: "فورنو فلفل اسود", sku: "CHP-010", category: "شيبسات ميني ماركت" },
  { nameAr: "فورنو جبنة", sku: "CHP-011", category: "شيبسات ميني ماركت" },
  { nameAr: "دوريتوس ديناميت", sku: "CHP-012", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز ماكس جبنة إيطالية", sku: "CHP-013", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز سيراتشا", sku: "CHP-014", category: "شيبسات ميني ماركت" },
  { nameAr: "طرزان", sku: "CHP-015", category: "شيبسات ميني ماركت" },
  { nameAr: "بيوقلز ناتشو", sku: "CHP-016", category: "شيبسات ميني ماركت" },
  { nameAr: "ستيكس حار", sku: "CHP-017", category: "شيبسات ميني ماركت" },
  { nameAr: "تاكيز", sku: "CHP-018", category: "شيبسات ميني ماركت" },
  { nameAr: "دوريتوس اسود", sku: "CHP-019", category: "شيبسات ميني ماركت" },
  { nameAr: "تسالي كاتشب", sku: "CHP-020", category: "شيبسات ميني ماركت" },
  { nameAr: "بيوقلز كاتشب", sku: "CHP-021", category: "شيبسات ميني ماركت" },
  { nameAr: "بيوقلز باربيكو", sku: "CHP-022", category: "شيبسات ميني ماركت" },
  { nameAr: "شيبس عمان", sku: "CHP-023", category: "شيبسات ميني ماركت" },
  { nameAr: "بيوقلز اوريجينال", sku: "CHP-024", category: "شيبسات ميني ماركت" },
  { nameAr: "تسالي حار", sku: "CHP-025", category: "شيبسات ميني ماركت" },
  { nameAr: "ليز جبنة", sku: "CHP-026", category: "شيبسات ميني ماركت" },
  { nameAr: "فلوتشي منوع", sku: "CHP-027", category: "شيبسات ميني ماركت" },
  { nameAr: "برنجلز حار", sku: "CHP-028", category: "شيبسات ميني ماركت" },
  { nameAr: "برنجلز كاتشب", sku: "CHP-029", category: "شيبسات ميني ماركت" },
  { nameAr: "برنجلز بصل", sku: "CHP-030", category: "شيبسات ميني ماركت" },
  { nameAr: "برنجلز جبنة", sku: "CHP-031", category: "شيبسات ميني ماركت" },
  { nameAr: "فانزلس", sku: "BSC-001", category: "بسكويت ميني ماركت" },
  { nameAr: "لواكر شوكلت", sku: "BSC-002", category: "بسكويت ميني ماركت" },
  { nameAr: "لواكر فانيلا", sku: "BSC-003", category: "بسكويت ميني ماركت" },
  { nameAr: "لواكر بندق", sku: "BSC-004", category: "بسكويت ميني ماركت" },
  { nameAr: "لواكر دارك شوكلت", sku: "BSC-005", category: "بسكويت ميني ماركت" },
  { nameAr: "لواكر سناك دارك شوكلت", sku: "BSC-006", category: "بسكويت ميني ماركت" },
  { nameAr: "بسكوت مملح", sku: "BSC-007", category: "بسكويت ميني ماركت" },
  { nameAr: "كريب ويفر", sku: "BSC-008", category: "بسكويت ميني ماركت" },
  { nameAr: "مارشميلو", sku: "BSC-009", category: "بسكويت ميني ماركت" },
  { nameAr: "توفي لك", sku: "BSC-010", category: "بسكويت ميني ماركت" },
  { nameAr: "بسكوت نجوم", sku: "BSC-011", category: "بسكويت ميني ماركت" },
  { nameAr: "بسكوت شوفان زيرو", sku: "BSC-012", category: "بسكويت ميني ماركت" },
  { nameAr: "ريكو", sku: "BSC-013", category: "بسكويت ميني ماركت" },
  { nameAr: "اولكر ساندوتش", sku: "BSC-014", category: "بسكويت ميني ماركت" },
  { nameAr: "كاجو", sku: "BSC-015", category: "بسكويت ميني ماركت" },
  { nameAr: "فصفص", sku: "BSC-016", category: "بسكويت ميني ماركت" },
  { nameAr: "وافل شو", sku: "BSC-017", category: "بسكويت ميني ماركت" },
  { nameAr: "كيكة ديمه فراولة", sku: "BSC-018", category: "بسكويت ميني ماركت" },
  { nameAr: "كب كيك ديمة فانيلا", sku: "BSC-019", category: "بسكويت ميني ماركت" },
  { nameAr: "هولز", sku: "CND-001", category: "حلويات ميني ماركت" },
  { nameAr: "لبان نعناع حار", sku: "CND-002", category: "حلويات ميني ماركت" },
  { nameAr: "لبان نعناع بارد", sku: "CND-003", category: "حلويات ميني ماركت" },
  { nameAr: "لبان الصاروخ", sku: "CND-004", category: "حلويات ميني ماركت" },
  { nameAr: "سكتلز حامضة", sku: "CND-005", category: "حلويات ميني ماركت" },
  { nameAr: "سكتلز توت", sku: "CND-006", category: "حلويات ميني ماركت" },
  { nameAr: "إكستريم زد فراولة", sku: "CND-007", category: "حلويات ميني ماركت" },
  { nameAr: "سي سي ستيك مانجا", sku: "CND-008", category: "حلويات ميني ماركت" },
  { nameAr: "سي سي ستيك فراولة", sku: "CND-009", category: "حلويات ميني ماركت" },
  { nameAr: "سي سي ستيك توت", sku: "CND-010", category: "حلويات ميني ماركت" },
  { nameAr: "شوكي شوكي", sku: "CND-011", category: "حلويات ميني ماركت" },
  { nameAr: "زي زاي فواكة", sku: "CND-012", category: "حلويات ميني ماركت" },
  { nameAr: "إكستريم زد", sku: "CND-013", category: "حلويات ميني ماركت" },
  { nameAr: "شوبا شوبس طويله", sku: "CND-014", category: "حلويات ميني ماركت" },
  { nameAr: "حلاوة برجر", sku: "CND-015", category: "حلويات ميني ماركت" },
  { nameAr: "حلاوة هوت دوج", sku: "CND-016", category: "حلويات ميني ماركت" },
  { nameAr: "ساور زنك فراولة", sku: "CND-017", category: "حلويات ميني ماركت" },
  { nameAr: "ساور زنك كولا", sku: "CND-018", category: "حلويات ميني ماركت" },
  { nameAr: "ساور زنك تفاح", sku: "CND-019", category: "حلويات ميني ماركت" },
  { nameAr: "مناديل", sku: "CND-020", category: "حلويات ميني ماركت" },
  { nameAr: "حلاوة ديدي", sku: "CND-021", category: "حلويات ميني ماركت" },
  { nameAr: "كندز ماكسي", sku: "CHO-001", category: "شوكولاتة ميني ماركت" },
  { nameAr: "كندر كارد", sku: "CHO-002", category: "شوكولاتة ميني ماركت" },
  { nameAr: "كندر بونو", sku: "CHO-003", category: "شوكولاتة ميني ماركت" },
  { nameAr: "كندر وايت", sku: "CHO-004", category: "شوكولاتة ميني ماركت" },
  { nameAr: "رافيلو", sku: "CHO-005", category: "شوكولاتة ميني ماركت" },
  { nameAr: "جالكسي بندق", sku: "CHO-006", category: "شوكولاتة ميني ماركت" },
  { nameAr: "جالكسي كراميل", sku: "CHO-007", category: "شوكولاتة ميني ماركت" },
  { nameAr: "جالكسي دارك", sku: "CHO-008", category: "شوكولاتة ميني ماركت" },
  { nameAr: "لواكر سناك بندق", sku: "CHO-009", category: "شوكولاتة ميني ماركت" },
  { nameAr: "بريك تايم", sku: "CHO-010", category: "شوكولاتة ميني ماركت" },
  { nameAr: "جالكسي فلوتس", sku: "CHO-011", category: "شوكولاتة ميني ماركت" },
  { nameAr: "كيت كات", sku: "CHO-012", category: "شوكولاتة ميني ماركت" },
  { nameAr: "كندر كاونتري", sku: "CHO-013", category: "شوكولاتة ميني ماركت" },
  { nameAr: "نوتيلا بيسكوت", sku: "CHO-014", category: "شوكولاتة ميني ماركت" },
  { nameAr: "نوتيلا ب ريدي", sku: "CHO-015", category: "شوكولاتة ميني ماركت" },
  { nameAr: "بيج بريك", sku: "CHO-016", category: "شوكولاتة ميني ماركت" },
  { nameAr: "مالتيزر", sku: "CHO-017", category: "شوكولاتة ميني ماركت" },
  { nameAr: "بيضة كندر", sku: "CHO-018", category: "شوكولاتة ميني ماركت" },
  { nameAr: "ميرندا حمضيات", sku: "JUC-001", category: "عصيرات ميني ماركت" },
  { nameAr: "ميرندا برتقال", sku: "JUC-002", category: "عصيرات ميني ماركت" },
  { nameAr: "شاني", sku: "JUC-003", category: "عصيرات ميني ماركت" },
  { nameAr: "سن كولا", sku: "JUC-004", category: "عصيرات ميني ماركت" },
  { nameAr: "ميرندا قزاز", sku: "JUC-005", category: "عصيرات ميني ماركت" },
  { nameAr: "كولا قزاز", sku: "JUC-006", category: "عصيرات ميني ماركت" },
  { nameAr: "كولا العادي", sku: "JUC-007", category: "عصيرات ميني ماركت" },
  { nameAr: "ريتا احمر", sku: "JUC-008", category: "عصيرات ميني ماركت" },
  { nameAr: "ريتا ازرق", sku: "JUC-009", category: "عصيرات ميني ماركت" },
  { nameAr: "ريتا باشن فروت", sku: "JUC-010", category: "عصيرات ميني ماركت" },
  { nameAr: "ربيع", sku: "JUC-011", category: "عصيرات ميني ماركت" },
  { nameAr: "حليب شوكلت", sku: "JUC-012", category: "عصيرات ميني ماركت" },
  { nameAr: "حليب فراولة", sku: "JUC-013", category: "عصيرات ميني ماركت" },
  { nameAr: "أناناس", sku: "JUC-014", category: "عصيرات ميني ماركت" },
  { nameAr: "تفاح", sku: "JUC-015", category: "عصيرات ميني ماركت" },
  { nameAr: "جوافة", sku: "JUC-016", category: "عصيرات ميني ماركت" },
  { nameAr: "كوكتيل", sku: "JUC-017", category: "عصيرات ميني ماركت" },
  { nameAr: "ايس تي زوي استوائي", sku: "JUC-018", category: "عصيرات ميني ماركت" },
  { nameAr: "ايس تي زوي خوخ", sku: "JUC-019", category: "عصيرات ميني ماركت" },
  { nameAr: "ايس تي زوي مانجا", sku: "JUC-020", category: "عصيرات ميني ماركت" },
  { nameAr: "ايس تي زوي توت", sku: "JUC-021", category: "عصيرات ميني ماركت" },
  { nameAr: "ببسي", sku: "JUC-022", category: "عصيرات ميني ماركت" },
  { nameAr: "سفن", sku: "JUC-023", category: "عصيرات ميني ماركت" },
  { nameAr: "سبرايت", sku: "JUC-024", category: "عصيرات ميني ماركت" },
  { nameAr: "سبرايت حمضيات", sku: "JUC-025", category: "عصيرات ميني ماركت" },
  { nameAr: "ليبتون خوخ", sku: "JUC-026", category: "عصيرات ميني ماركت" },
  { nameAr: "ليبتون توت", sku: "JUC-027", category: "عصيرات ميني ماركت" },
  { nameAr: "ببريكان فراولة", sku: "JUC-028", category: "عصيرات ميني ماركت" },
  { nameAr: "ديو", sku: "JUC-029", category: "عصيرات ميني ماركت" },
];

