// Auto-generated from the warehouse inventory workbook (last count).
// Item names are copied verbatim from the sheet (Arabic).
export const IMPORT_CATEGORIES = [
  "مواد غذائية عامة",
  "صوصات",
  "مجمدات",
  "حلويات",
  "بلاستيكات ومستهلكات",
] as const;

export type ImportItem = { nameAr: string; sku: string; category: string };

export const IMPORT_ITEMS: ImportItem[] = [
  { nameAr: "صلصه طماطم", sku: "GEN-001", category: "مواد غذائية عامة" },
  { nameAr: "قشطه حلى", sku: "GEN-002", category: "مواد غذائية عامة" },
  { nameAr: "نستله", sku: "GEN-003", category: "مواد غذائية عامة" },
  { nameAr: "تونه الوها", sku: "GEN-004", category: "مواد غذائية عامة" },
  { nameAr: "فانيلا", sku: "GEN-005", category: "مواد غذائية عامة" },
  { nameAr: "جبنه سائله", sku: "GEN-006", category: "مواد غذائية عامة" },
  { nameAr: "لازانيا فرشلي", sku: "GEN-007", category: "مواد غذائية عامة" },
  { nameAr: "مكرونه اسباغتي", sku: "GEN-008", category: "مواد غذائية عامة" },
  { nameAr: "مكرونه فوتشيني", sku: "GEN-009", category: "مواد غذائية عامة" },
  { nameAr: "مكرونه اقلام", sku: "GEN-010", category: "مواد غذائية عامة" },
  { nameAr: "مكرونه حلزونيه", sku: "GEN-011", category: "مواد غذائية عامة" },
  { nameAr: "رزتو", sku: "GEN-012", category: "مواد غذائية عامة" },
  { nameAr: "شعيريه", sku: "GEN-013", category: "مواد غذائية عامة" },
  { nameAr: "مسحوق ماجى", sku: "GEN-014", category: "مواد غذائية عامة" },
  { nameAr: "مسحوق بهارات كنور", sku: "GEN-015", category: "مواد غذائية عامة" },
  { nameAr: "اندومي دجاج", sku: "GEN-016", category: "مواد غذائية عامة" },
  { nameAr: "اندومي ابيض", sku: "GEN-017", category: "مواد غذائية عامة" },
  { nameAr: "اندومي كاسات خضار", sku: "GEN-018", category: "مواد غذائية عامة" },
  { nameAr: "اندومي كاسات دجاج", sku: "GEN-019", category: "مواد غذائية عامة" },
  { nameAr: "شيبس عمان", sku: "GEN-020", category: "مواد غذائية عامة" },
  { nameAr: "اكياس عدس", sku: "GEN-021", category: "مواد غذائية عامة" },
  { nameAr: "عسل", sku: "GEN-022", category: "مواد غذائية عامة" },
  { nameAr: "خل بلسمك", sku: "GEN-023", category: "مواد غذائية عامة" },
  { nameAr: "ورشستر", sku: "GEN-024", category: "مواد غذائية عامة" },
  { nameAr: "خل", sku: "GEN-025", category: "مواد غذائية عامة" },
  { nameAr: "بهار الكاجون صغير", sku: "GEN-026", category: "مواد غذائية عامة" },
  { nameAr: "بهار الكاجون كبير", sku: "GEN-027", category: "مواد غذائية عامة" },
  { nameAr: "كرتون سكر ابض", sku: "GEN-028", category: "مواد غذائية عامة" },
  { nameAr: "زيت زيتون", sku: "GEN-029", category: "مواد غذائية عامة" },
  { nameAr: "دقيق كويتي", sku: "GEN-030", category: "مواد غذائية عامة" },
  { nameAr: "زيت", sku: "GEN-031", category: "مواد غذائية عامة" },
  { nameAr: "شاهي اخضر", sku: "GEN-032", category: "مواد غذائية عامة" },
  { nameAr: "رانش", sku: "SAU-001", category: "صوصات" },
  { nameAr: "مايونيز", sku: "SAU-002", category: "صوصات" },
  { nameAr: "خردل", sku: "SAU-003", category: "صوصات" },
  { nameAr: "صوص فرنسي", sku: "SAU-004", category: "صوصات" },
  { nameAr: "بيستو", sku: "SAU-005", category: "صوصات" },
  { nameAr: "صوص برقر", sku: "SAU-006", category: "صوصات" },
  { nameAr: "شنطة رنا", sku: "SAU-007", category: "صوصات" },
  { nameAr: "كاتشب", sku: "SAU-008", category: "صوصات" },
  { nameAr: "فيليه", sku: "FRZ-001", category: "مجمدات" },
  { nameAr: "بطاطس", sku: "FRZ-002", category: "مجمدات" },
  { nameAr: "شباتي", sku: "FRZ-003", category: "مجمدات" },
  { nameAr: "مسحب", sku: "FRZ-004", category: "مجمدات" },
  { nameAr: "بوب كورن", sku: "FRZ-005", category: "مجمدات" },
  { nameAr: "برقر", sku: "FRZ-006", category: "مجمدات" },
  { nameAr: "كرسبي", sku: "FRZ-007", category: "مجمدات" },
  { nameAr: "صدور دجاج", sku: "FRZ-008", category: "مجمدات" },
  { nameAr: "جبنة موزريلا", sku: "FRZ-009", category: "مجمدات" },
  { nameAr: "حلوم", sku: "FRZ-010", category: "مجمدات" },
  { nameAr: "نقانق", sku: "FRZ-011", category: "مجمدات" },
  { nameAr: "كيك ديمة  براوني", sku: "DES-001", category: "حلويات" },
  { nameAr: "كيكة ديمه شكولاته", sku: "DES-002", category: "حلويات" },
  { nameAr: "كيكة ديمه ازرق", sku: "DES-003", category: "حلويات" },
  { nameAr: "كيك اوريو", sku: "DES-004", category: "حلويات" },
  { nameAr: "بسكوت مالح", sku: "DES-005", category: "حلويات" },
  { nameAr: "بسكوت اعواد", sku: "DES-006", category: "حلويات" },
  { nameAr: "كيكة جالكسي", sku: "DES-007", category: "حلويات" },
  { nameAr: "اكواب بورتل ابيض", sku: "DIS-001", category: "بلاستيكات ومستهلكات" },
  { nameAr: "اكواب بورتل صغير", sku: "DIS-002", category: "بلاستيكات ومستهلكات" },
  { nameAr: "اكواب حمرا", sku: "DIS-003", category: "بلاستيكات ومستهلكات" },
  { nameAr: "اكواب شفافة بررتل", sku: "DIS-004", category: "بلاستيكات ومستهلكات" },
  { nameAr: "امواب شفاف عصير", sku: "DIS-005", category: "بلاستيكات ومستهلكات" },
  { nameAr: "فناجيل  قهوه", sku: "DIS-006", category: "بلاستيكات ومستهلكات" },
  { nameAr: "مصاصات", sku: "DIS-007", category: "بلاستيكات ومستهلكات" },
  { nameAr: "قفازات", sku: "DIS-008", category: "بلاستيكات ومستهلكات" },
  { nameAr: "اغطية راس", sku: "DIS-009", category: "بلاستيكات ومستهلكات" },
  { nameAr: "اكياس بيع", sku: "DIS-010", category: "بلاستيكات ومستهلكات" },
  { nameAr: "ورق شفاف  ساندوتشات", sku: "DIS-011", category: "بلاستيكات ومستهلكات" },
  { nameAr: "ورق قصدير سندوتشات", sku: "DIS-012", category: "بلاستيكات ومستهلكات" },
  { nameAr: "قصدير", sku: "DIS-013", category: "بلاستيكات ومستهلكات" },
  { nameAr: "شفاف تغليف", sku: "DIS-014", category: "بلاستيكات ومستهلكات" },
  { nameAr: "صحون ورق صغير", sku: "DIS-015", category: "بلاستيكات ومستهلكات" },
  { nameAr: "صحون ورق كبير", sku: "DIS-016", category: "بلاستيكات ومستهلكات" },
  { nameAr: "صحون بلاستيك", sku: "DIS-017", category: "بلاستيكات ومستهلكات" },
  { nameAr: "صحون اسود بغطا", sku: "DIS-018", category: "بلاستيكات ومستهلكات" },
  { nameAr: "مناديل استخدام", sku: "DIS-019", category: "بلاستيكات ومستهلكات" },
  { nameAr: "مناديل مربعه", sku: "DIS-020", category: "بلاستيكات ومستهلكات" },
];

